### PR TITLE
Support Laravel 11

### PR DESCRIPTION
**Pull request by MaxGiting**
Adds Laravel 11 support to v1.

### CODE REVIEW

**Comment by driesvints** [comment]
I'm sorry but I'm only maintaining v2 atm.

**Comment by MaxGiting** [comment]
That's a shame as bumping the Heroicons dependency to v2 is a stylistic choice as mentioned in their docs.

> Heroicons v2.0 is a brand new icon set with a different visual style, so don't feel like you need to upgrade to avoid "being on the old version".

I was hopeful you would merge this PR as it was solely bumping composer dependencies to allow newer Laravel apps to continue to use this stylistic choice and nothing more technical.

Thank you for your time and work on this package.

**Comment by driesvints** [comment]
Okay sure thing. No biggy 👍

**Comment by MaxGiting** [comment]
Thank you

**Pull request closed without merging**
