### PR TITLE
Update heroicons v2

### PR DESCRIPTION
**Pull request by duongtdvn**
I have added/updated all new icons from the optimized directory without the mini (20px) set.

### CODE REVIEW

**Comment by Jubeki** [comment]
Maybe the prefix `sm-` can be used for the small icon set?

**Comment by duongtdvn** [comment]
I was thinking about `ms-` which stands for mini solid since there is only a solid set by now, but maybe someday they will release the outline set so in which case we can use the `mo-`. However, `sm-` and `om-` are also good choices.

**Comment by driesvints** [comment]
I added the mini icons with the `m-` prefix. As long as there's no outline version of them there's nothing to worry about I think.

**Comment by driesvints** [comment]
Thanks!

**Comment by Jubeki** [comment]
So just to clarify I meant `sm` as in small and not as `solid mini` but I can see that that is a little confusing in the context.

I am completely fine with only the `m` Prefix (2.0.0 of blade-heroicons is already released, so that would be a little late for changing that)

I also don't think that there will be another set type (small outline) for heroicons soon.

**Comment by driesvints** [comment]
If there's another set we can name it m-o- or something

**Pull request merged**
